---
# tasks file for sap-netweaver-preconfigure: installation

- name: Ensure required packages are installed
  package:
    state: present
    name: "{{ __sap_netweaver_preconfigure_packages }}"

...
