---
# Ensure {{ sap_diagagent_agent_tmp_directory }} directory is removed from the target host
- name: Ensure {{ sap_diagagent_agent_tmp_directory }} directory does not exist
  file:
    path: "{{ sap_diagagent_agent_tmp_directory }}"
    state: absent
    mode: '0755'
  when: sap_diagagent_clean_tmp_directory
