---

# Ensure {{ sap_diagagent_agent_tmp_directory }} directory exists on the target host
- name: Ensure {{ sap_diagagent_agent_tmp_directory }} directory exists
  file:
    path: "{{ sap_diagagent_agent_tmp_directory }}"
    state: directory
    mode: '0755'